### ISSUE TITLE
Change the actual CPU governor

### ISSUE THREAD

**Issue by hotice** [pyamsoft/pstate-frequency#5] opened 2014-10-24 12:18 UTC
I see that pstate-frequency uses its own governors (powersave, performance and max-performance) and it doesn't changes actual CPU governors (performance and powersave only for Intel P-State). Why exactly is that? And do you plan to allow pstate-frequency to actually change the Intel P-state CPU governor?

I want to write about pstate-frequency on WebUpd8 but I find this confusing... so some clarifications would be nice. Thanks!

**Comment by pyamsoft** [comment] 2015-01-07 00:17
As of kernel 3.19.rc2 I have been unable to reproduce this problem. Setting the frequencies using the powersave plan produces printouts from both /proc/cpuinfo and the i7z tool as expected.

The machine runs slower with the powersave plan, with compile times and other system activities being significantly reduced in performance as well, and the power consumption of the machine as measured by powertop and powerstat over a period of a couple of minutes is indeed reduced compared to running with the performance plan. 

With the recent changes to the intel_pstate module in the new kernel 3.19 I believe this problem has been resolved, and as such I am closing the issue.

**Closed by pyamsoft** 2015-01-07 00:17 UTC
Labels: bug, wontfix
